project:
  type: website
  resources:
        - "exercises"
        - "slides"
        - "SPSS_datasets"
  output-dir: docs
  
website:
  title: "CAP Pathway: Intro to Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: session1.qmd
        text: Session 1
      - href: session2.qmd
        text: Session 2
      - href: session3.qmd
        text: Session 3
    tools:
      - icon: link  # Use a generic link icon, as there's no specific Bluesky icon
        href: https://bsky.app/profile/liamjbhill.bsky.social  # Replace with your Bluesky URL
      - icon: github
        href: https://github.com/Liam-JB-Hill/CAP_pathway_Intro_to_Stats
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Liam JB Hill"

format:
  html:
    theme: cerulean
    toc: true

editor: source

