project:
  type: website
  output-dir: docs
  
website:
  title: "CAP Pathway: Intro to Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://bsky.app/profile/liamjbhill.bsky.social
      - icon: github
        href: https://github.com/Liam-JB-Hill/CAP_pathway_Intro_to_Stats
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Liam JB Hill"

format:
  html:
    theme: cerulean
    toc: true

editor: source

