---
title: ""
format: 
  html:
    toc: false  # Table of contents (sidebar) hidden
    css: styles.css  # Optional: add custom styles
    number-sections: false
    theme: spacelab  # You can choose a different theme
    background: white
    code-fold: true  # Option to fold code blocks
---

This website hosts supporting materials for a single day summer school, which I run for *MSc Education Child & Adolescent Psychology (CAP) Pathway* students within MHSES, at the University of Edinburgh.

The content is broken up into three sessions, which are designed to give you an introduction to foundational statistical concepts and teach you some simple descriptive and inferential statistical methods.

# Schedule for the day

0900-1030: **Session 1:** Describing, Visualising and Exploring Data

1100-1230: **Session 2:** The theory underpinning frequentist inferential statistical methods

1400-1600: **Session 3:** An introduction to inferential statistical tests

<br>

::: {.callout-important}
## IMPORTANT - Looking into this before the day of the summer-school!

**Please bring with you to the summer-school a device (e.g. a laptop) that has SPSS already set up and running on it.** 

SPSS is a statistical software that you will practice using in Sessions 1 and 3. *We will NOT have time to go through installing it on the day, so please find time to do this beforehand.*

The University has procedures that will allow you to request and install a FREE personal copy of this software. Further instructions on how to do this can be found at this Information Services Webpage: <https://information-services.ed.ac.uk/computing/desktop-personal/software/main-software-deals/spss/spss-staff-and-students>
:::


